version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:8d:ab:30:c1:8b:9a:0e:98:d4:0f:3d:eb:59:26:b6"
      - checkout
      - run:
          name: echo version of java
          command: java --version
      - run:
          name: echo version of gradle
          command: gradle --version
      # - run: gradle build
      # - run:
          # name: Add known hosts
          # command: ssh-keyscan circleci.com >> ~/.ssh/known_hosts
      - run:
          name: Add SSH host to known
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            SSH_DEPLOY_PATH=/apps/my-app
            scp -r ./* "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls"
    
  # test:
    # docker:
      # - image: cimg/openjdk:20.0.1
    # steps:
      # - run: gradle test


workflows:
  build_test:
    jobs:
      - build
      # - approval:
          # type: approval
          # requires:
            # - build
      # - test:
      #     requires:
      #       - build
            # - approval
