version: 2.1

parameters:
  working_directory: &wd
    ~/project

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: *wd
    steps:
      - checkout
      - run:
          name: echo version of java
          command: java --version
      - run:
          name: echo version of gradle
          command: gradle --version
      - run: gradle build
  test:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: *wd
    steps:
      - run: gradle test


workflows:
  build_test:
    jobs:
      - build
      - approval:
          type: approval
          requires:
            - build
      - test:
          requires:
            - build
            - approval
