version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg:openjdk:20.0.1
    steps:
      - run: |
          echo "This is pipeline.id values: << pipeline.id >>"
      - run:
          name: echo pipeline.git_url
          command: |
            echo "This is pipeline.git_url: << pipeline.git_url >>"

workflows:
  simple-job:
    jobs:
      - my-job