version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b0:7e:23:06:ad:53:ad:b9:45:56:43:bd:62:7a:d1:94"
      - checkout
      # - run:
      #     name: echo version of java
      #     command: java --version
      # - run:
      #     name: echo version of gradle
      #     command: gradle --version
      # - run: gradle build
      # - run:
          # name: Add known hosts
          # command: ssh-keyscan circleci.com >> ~/.ssh/known_hosts
      - run:
          name: Add SSH host to known
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            SSH_DEPLOY_PATH=/home/ubuntu/
            scp ./* "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       rsync -avce ssh build $SSH_USER@$SSH_HOST "ls"
    
  # test:
    # docker:
      # - image: cimg/openjdk:20.0.1
    # steps:
      # - run: gradle test


workflows:
  build_test:
    jobs:
      - build
      # - approval:
          # type: approval
          # requires:
            # - build
      # - test:
      #     requires:
      #       - build
            # - approval
