version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: echo version of java
          command: java --version
      - run:
          name: echo version of gradle
          command: gradle --version
      - run: gradle test
      - run: echo "<< pipeline.trigger_parameters.github_app.commit_message >>"