version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/project
    steps:
      - checkout
      - run: java --version
      - run: gradle --version
      - run: gradle test