version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/project
    steps:
      - checkout
      - run: java --version
      - run: gradle --version
      - run: gradle test
      - run: echo "<< pipeline.trigger_parameters.github_app.commit_author_name >>"
      - run: echo "<< pipeline.trigger_parameters.github_app.commit_author_email >>"